# Delete this file when Aptfile stops using a PPA

[[io.buildpacks.group]]
id = "panoviewer/ppa-hack"

[io.buildpacks.group.script]
api = "0.9"
inline="""
echo '-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: Hostname:
Version: Hockeypuck 2.1.1-10-gec3b0e7

xo0EUp3DIQEEAMVlgB86QmCRyqdO1zXl8vnt9N1jfXO7JUURCDDOO8g71B4HXhue
tIZw1N2LUsvSI3CRv/z7uf/sUmn/R1J6rFsCqYAiZYKO1W917AGcBUPX0dIjiKM/
RKe3khKoHEwRGJpQHbOe3kXtJhMqqrP/pFWD1iY65TawcTLJqLLBv5UxABEBAAHN
G0xhdW5jaHBhZCBQUEEgZm9yIFBhbmRhIEppbcK4BBMBAgAiBQJSncMhAhsDBgsJ
CAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRBMHL4UhSVBy4E7A/9FlkunlAd/Sp47
CzNaOfPnfyEYgzDf5mW1dI434qW4zwa2XuNQQRszEancVsfu0JRwCHzd3aelEDAS
FyyXtMPG5jXs14c4auXEmFuppBU48oCfATiGdEu9yL1ayagF2PDBZZgoTVyBf4gk
66pZyO3ir/c4Zad3o+ClnzWNdzXJag==
=vUBr
-----END PGP PUBLIC KEY BLOCK-----' > /etc/apt/trusted.gpg.d/ubuntuhandbook1.asc
"""
